
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ccp_development
  pool: 5
  username: root
  password: 
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ccp_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ccp
  pool: 5
  username: ccp
  password: lima1234
  socket: /var/run/mysqld/mysqld.sock